### ISSUE TITLE
Reference Only: SOLUTION for user gets 404 when attempting to view their Achievements page

### ISSUE THREAD

**Issue by DanDawson** [paulgibbs/achievements#140]
**VERSIONS:**
WordPress 3.9, Achievements 3.5.1, iThemes Security 4.1.3

**SETUP:**
Permalinks structure set to Custom: /%category%/%postname%/  
I attempted various other Permalink options and re-saved them and had not change in behavior. 

**PROBLEM:**
A user who has completed an achievement clicks the My Achievements link which points to:

http://[domain]/author/[username]/achievements/

And receives a 404.  If I change the Permalinks to default the URL is:

http://[domain]/?author=101/achievements

and still gives a 404.

And during testing I notice that the following URL does work properly:

http://[domain]/achievements/

**SOLUTION FOUND:**
One of the plugins installed was iThemes Security, and one of the settings in that plugin is "Disables a user's author page if their post count is 0."  If that is turned on, and the Author has zero posts, they can't see their Achievement page.  Uncheck the box, save changes, and the URL to their Achievements page works :-)

**TROUBLESHOOTING METHOD:**
Played with permalink settings with no luck. Disabled all plugins, it worked. Re-enabled all and then one by one, starting with the most likely culprits, disabled the plugins until it worked.  Once I knew which plugin, I started working through the plugin settings in a similar fashion.  

Hope this helps someone in the future :-)

**Comment by paulgibbs** [comment]
HI Dan

Thanks for using the plugin (and sticking with it), and for letting me know about this option in iThemes Security. :)
