### ISSUE TITLE
dpa_is_running_networkwide not declared before being used on MS install

### ISSUE THREAD

**Issue by sboisvert** [paulgibbs/achievements#19]
line 224 of chievements.php of current trunk 
if ( is_multisite() && dpa_is_running_networkwide() ) 
since in 
public static function instance() 
the line 
self::$instance->setup_globals();
is before 
self::$instance->includes();
while trying to activate the plugin on 3.4 MS with BP 1.5.something you will get a function undefined fatal error. to fix this I just changed the order to have the includes() before the setup_globals() and everything worked.... (seems to for now atleast....)
This might not be the best solution and perhaps I just broke a bunch of things but you are probably in a better position to be the judge of that!

Thanks!

**Comment by paulgibbs** [comment]
Thanks for the report. I haven't tested on multisite in a while, so I'll do that. Do you still have a copy of the fatal error message, so we can see exactly what it's complaining about?

**Comment by sboisvert** [comment]
It was on plugin activation in Multisite in network admin in plugins when clicking on network activate it would return "cannot activate plugin caused a fatal error etc"

**Comment by paulgibbs** [comment]
Confirmed.
