### ISSUE TITLE
Create/add dashboard icon

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/achievements#2]

**Comment by vfowler** [comment]
As mentioned in http://wordpress.org/support/topic/change-menu-icon-for-achievements-in-dashboard?replies=2#post-4199430 please add a filter such that a custom dashboard menu icon can overwrite the default menu icon.

This is useful in communities where multiple users with appropriate roles and capabilities have access to several custom post types and they all have the same menu icon. Being able to distinguish them is important for UX and being able to have a custom menu icon means Achievements can be branded with how each community uses it.

**Comment by paulgibbs** [comment]
It's been a year since I made this, and I still haven't learnt to draw, so going to close the ticket.

**Comment by vfowler** [comment]
Thanks for your time Paul. I'll check it out when I'm back from leave.
