### ISSUE TITLE
Add support for "hidden" achievements

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/achievements#34]
These won't be listed on the achievements archive page, but the URL is accessible if you know of it.

Not sure if best to implement with a post status or a post meta item.

**Comment by paulgibbs** [comment]
Review post-WP 3.6 to see if post statuses make sense.

**Comment by mikebronner** [comment]
:+1: to this. Would love to see hidden achievements for some use cases I have as well.

**Comment by BronsonQuick** [comment]
I'm planning on having a crack at this tomorrow. Seeing post statuses seemed to stall in 3.6 I was wondering how you'd like this implemented. I was thinking that there are two options:
1. I can have a look at how Edit Flow implements Post Status and try and extract some of their code and bundle it into Achievements. (This obviously more complex and robust)
2. I could simply add a checkbox for Hidden into the Publish metabox and work that into the code. (The low hanging fruit)

Let me know what you'd prefer Paul and I'll have a crack either tomorrow or Monday :grin:

**Comment by paulgibbs** [comment]
Ideally I would like a new item added in the regular "post status" dropdown on the Add New Post screen. Looking at Edit Flow might be a good idea to see how Daniel managed to do this. When I looked a few releases of WordPress ago, this wasn't possible, but I live in hope :)

If the Edit Flow approach is anything big like e.g. removing the default form option, and inserting a custom version of the "post status" dropdown... clearly there would be compatibility problems if e.g. Achievements and Edit Flow were trying to do the same thing. In this case, I'd probably suggest thinking about inserting the custom status into the dropdown with JavaScript.

The checkbox solution would probably end up storing the toggle as post meta, and then most queries to Achievements would need to check for this post meta... causing joins, if we aren't fetching meta anywhere already. This is my least favourite idea, as it seems that this sort of thing is perfect for post statuses.

**Comment by paulgibbs** [comment]
Forgot to say, big thanks for taking a look into this! :)

**Comment by rmccue** [comment]
I took a look into this on @BronsonQuick's behalf.

Edit Flow does a tonne of hacky stuff, including messing with the post status dropdown using Javascript. Unfortunately, core support for this got bumped with the editorial flow stuff. (Relevant ticket for this is [#12706](https://core.trac.wordpress.org/ticket/12706))

Until we can comfortably mess around with post statuses, I've opted to use the private post status and work in support for that. It's a [small patch](https://gist.github.com/rmccue/5727154), but we have to filter the post statuses locally, since WP doesn't like us passing in `'post_status' => array( 'publish', 'private')`

If you're happy to go down that route, I can whip up a pull request for it.

**Comment by paulgibbs** [comment]
So. :)

This seems to work OK for private award-type achievements, but for private event-type achievements, it doesn't work. There's some quirk in WordPress that I haven't run into before, and haven't been able to track it down yet.

When you assign a term to a private achievement, the wp_term_taxonomy.count record for that term is NOT incremented. In turn, this causes the get_terms() call in dpa_register_events() to not return anything, thus breaking the event achievement :)

**Comment by paulgibbs** [comment]
I think it is to do with _update_post_term_count() which is specified in the register_taxonomy() call in achievements.php. I think the fix is to create my own _update_post_term_count, and tweak the original -- there's a post_status = publish check, which I think is the cause.
