### ISSUE TITLE
Fatal error in theme-compatibility.php

### ISSUE THREAD

**Issue by erlend-sh** [paulgibbs/achievements#50]
I'm trying to test Achievements 3 with the latest version of PressCrew's Balance theme. It activates just fine, but when I try to go to /achievements, it returns this error:
Fatal error: Function name must be a string in /var/www/test/org/wp-content/plugins/achievements-3.0-beta-2/includes/core/theme-compatibility.php on line 697

**Comment by paulgibbs** [comment]
Thanks for the reporting. Interesting:  

1) The achievements plugin directory must be called "achievements". Github downloads give it a funny name, and the current lack of documentation doesn't make things clear. :)   Deactivate the plugin before renaming the folder.

2) If issue persists, please can you try disabling Achievements and try activating the bbPress plugin? Do you get a fatal error from bbPress, to?
I ask because this error comes from some code I took from bbPress.

Thanks

## 

Paul Gibbs

**Comment by erlend-sh** [comment]
Oh yeh, I actually tested with the renamed directory on first install, forgot to mention that part. That setup did not work either. After deactivating the plugin, renaming it to "achievements" and activating it, it returns this error within the plugins page:
Warning: require(/var/www/test/org/wp-content/plugins/achievements-3.0-beta-2/includes/class-dpa-extension.php): failed to open stream: No such file or directory in /var/www/test/org/wp-content/plugins/achievements-3.0-beta-2/achievements.php on line 266 Fatal error: require(): Failed opening required '/var/www/test/org/wp-content/plugins/achievements-3.0-beta-2/includes/class-dpa-extension.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/test/org/wp-content/plugins/achievements-3.0-beta-2/achievements.php on line 266

And no, no errors from bbPress either. We've been using that plugin together with the Balance site on our live site (jmonkeyengine.org) for a while now.

**Comment by paulgibbs** [comment]
If you renamed the directory, and de/re-activated the plugin, I don't know why it would be looking in "achievements-3.0-beta-2" still (as you can see from reading the error).  

Thanks for confirming bbPress works fine.

Are you running on a site/database that used to run the old version of Achievements (2.x)? If so, have you got any custom code snippets or helper plugins around?  

## 

Paul Gibbs

**Comment by erlend-sh** [comment]
Trying to activate it this morning, it appears to find the correct path and
no error is thrown, so that was probably just a server thing.

I'm still getting that error though:
Fatal error: Function name must be a string in
/var/www/test/org/wp-content/plugins/achievements/includes/core/theme-compatibility.php
on line 697

**Comment by erlend-sh** [comment]
Aha, my bad. I thought I had deleted the old Achievements plugin completely, but it appears the self-made 'Achievements' page was still present. After deleting that, everything worked fine on the Default theme as well as Balance.

Ultimately a user error, but an explicit check to make the transition easier for other users of the old plugin could be handy.

**Comment by paulgibbs** [comment]
Migration of data will be a focus in a future release post-3.0.
