### ISSUE TITLE
Network wide Activation results in Error

### ISSUE THREAD

**Issue by mrjarbenne** [paulgibbs/achievements#54]
Perhaps given that this plugin does not rely on BP anymore, I shouldn't be thinking about it as a Network Activated plugin, but a site by site plugin. I tried to activate it on a multisite install from the Network admin and got this error.

Fatal error: Call to undefined function is_plugin_active_for_network() in /home/verified/public_html/wp-content/plugins/achievements/achievements.php on line 667

Activating on the blog by blog basis works fine. 

Thanks Paul.

**Comment by paulgibbs** [comment]
Howdy. The bug with activating it in multisite was fixed very recently, and there will be another beta out by the end of the week.

This is how it's meant to work: in multisite, if you activate it on a single-site, you have separate Achievements installations. If you activate it network-wide, you get a shared Achievements install for all sites.

**Comment by mrjarbenne** [comment]
Thank you Mr. Gibbs.
