### ISSUE TITLE
3.0-rc-1 No Directory Page

### ISSUE THREAD

**Issue by modemlooper** [paulgibbs/achievements#59]
Same thing is happening as before. This time I installed on 1.6.3 that never had Achievements. Plugin activates without error but there is no notice to create the directory page. BuddyPress > Pages does not have achievements in the list.

**Comment by paulgibbs** [comment]
Achievements 3 doesn't require BuddyPress; it won't appear in the page mapping.

You should just go to example.com/achievements/ -- if you have something using the "achievements" page/post slug, you'll need to delete that.

**Comment by modemlooper** [comment]
Was it suppose to auto create the page?

**Comment by paulgibbs** [comment]
It doesn't create a Page (it doesn't need one). Just like how the bbPress plugin doesn't need a "forums" page.

If .com/achievements/ isn't working, try checking that your permalinks have been set to something other than the default.

**Comment by modemlooper** [comment]
http://dev.taptappress.com/achievements/

**Comment by modemlooper** [comment]
weird, I created the page then deleted it and then it worked. But http://dev.taptappress.com/achievements/two-faves/

**Comment by paulgibbs** [comment]
Huh. Weird.

I suppose this is a problem with the permalinks not being cleared correctly after the plugin has been activated. I have seen this once or twice in development but have been unable to recreate it so far :(

**Comment by modemlooper** [comment]
Ok, I guess it is working. However, the single achievement page is very sparse when no one has unlocked it. I suggest including the featured image on the single achievement page as the badge. Or are you doing away with the badges?

**Comment by paulgibbs** [comment]
I am using WP's Featured Image support for the badge icons. Early versions of 3.0 did pull the Featured Image in as part of the template. However, I decided against this as the achievement author lost control over the achievement's content (and it felt a bit weird in practice).

If you use a theme like twentyten, and set the achievement's Featured Image to the correct sized image for twentyten's headers, that works as you'd expect.

BP-Default and twentytwelve are two notable themes that don't support Featured Images on Page templates, so for these, I expect people will manually insert the images into the content area.
