### ISSUE TITLE
Page template override

### ISSUE THREAD

**Issue by modemlooper** [paulgibbs/achievements#63]
Maybe I'm not doing it right, when including archive-achievements.php in active theme folder it should use this as the page template but I can't seem to get it to use this file.

**Comment by paulgibbs** [comment]
This works for me. Creating content-archive-achievement.php in the root theme directory, or in e.g. /twentyten/achievements/content-archive-achievement.php overrides the theme compat template for the directory template, as it should.

If you mean you want to override which template Achievements injects its theme compat templates into, take a look at dpa_get_theme_compat_templates().
