### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by paulgibbs** [paulgibbs/achievements#95]

**Comment by mikebronner** [comment]
I'm with you on this. Was thinking of the same thing earlier today wondering how I'm going to test so many different branches.

**Comment by paulgibbs** [comment]
Got a working environment committed now; no tests yet. Since testing the actual unlocking of achievements might be very very tricky, I think the first focus will be making it possible to create and update achievements (incl. the custom meta), and making sure that works. Will need to create some API functions for this first as none exist.

Then I think I will focus on things like manually awarding achievements, and checking that progress is handled correctly.
