### ISSUE TITLE
WP Pro Quiz Support

### ISSUE THREAD

**Issue by jasperf** [paulgibbs/achievements#97]
Would it be possible to return support for WP Pro Quiz. Seems that an earlier version did, but current 3.2.2 does not. If not, is there any documentation out there to take care of this?

**Comment by paulgibbs** [comment]
v2 never supported this plugin. I'll review this plugin soon and see if it seems possible and good enough to add support in core for.

**Comment by paulgibbs** [comment]
WP Pro Quiz doesn't have enough WP actions to hook into, which is required for the plugin to work with Achievements, so this is a blocker for even considering adding support to the core plugin.
